### ISSUE TITLE
Prometheus-2 support

### ISSUE THREAD

**Issue by xukai92** [instructlab/eval#11]
this commit (https://github.com/xukai92/FastChat/commit/5d442955de7792d635719e9998972ee1c404a2d4) is needed for https://huggingface.co/prometheus-eval/prometheus-8x7b-v2.0 and should only be triggered for it

**Comment by ktam3** [comment]
@alimaredia

**Comment by danmcp** [comment]
Fix was included here: https://github.com/instructlab/eval/pull/9/commits/68185e4bf68adf7fdc53ce3d678f036f1ae1aedf
