### ISSUE TITLE
Add `instructlab.eval.constants` objects, would like access to `ALL_MMLU_TASKS` and similar

### ISSUE THREAD

**Issue by JamesKunstle** [instructlab/eval#25]
It'd be useful if I could pass a constant to the evaluator to tell it to "do vanilla, all tasks". 

This could be the default as well- by default, people would probably want the holistic score, but they could alternatively do fewer tasks.

```
evaluator = MMLUEvaluator(
                model_path,
                tasks=ALL_MMLU_TASKS,
                few_shots=2,  # TODO need to know this param
                batch_size=torch.cuda.device_count(),
            )
```

**Comment by nathan-weinberg** [comment]
@JamesKunstle does this fit the bill? https://github.com/instructlab/eval/pull/24
