### ISSUE TITLE
[Epic] CLI Integration (July 15 GA)

### ISSUE THREAD

**Issue by ktam3** [instructlab/eval#28]
- [x] #1369
- [x] #1 
- [x] #13 
- [x] #14 
- [x] #43 
- [x] #44

**Comment by nathan-weinberg** [comment]
Related PRs:
- https://github.com/instructlab/eval/pull/1
- https://github.com/instructlab/eval/pull/14
- https://github.com/instructlab/instructlab/pull/1369 (collaboration with @cdoern and @danmcp)

**Comment by cdoern** [comment]
We already have a backend command epic for the cli, is this a duplication of that?

**Comment by ktam3** [comment]
> We already have a backend command epic for the cli, is this a duplication of that?

i'll defer to nathan, my purpose for this epic is to track eval work related to CLI

**Comment by nathan-weinberg** [comment]
I think they can both exist - there may be some overlap in PRs but I don't see that as an issue

**Comment by ktam3** [comment]
@nathan-weinberg any other open tasks related to this epic?

**Comment by nathan-weinberg** [comment]
@ktam3 it's closed now but this one! https://github.com/instructlab/eval/issues/43

**Comment by nathan-weinberg** [comment]
This is the related PR - not sure if you want PRs or Issues: https://github.com/instructlab/eval/pull/44

**Comment by ktam3** [comment]
i'll take em all, thanks!
