### ISSUE TITLE
Ensure that SDG path data branch matches evaluation branch 

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/eval#35]
We need to ensure the SDG path data we are receiving is being generated off the same branch we are passing for evaluation.

I have some sample data that indicates this is tracked in the SDG data in the form of `origin_branch_name`.

We need to meet with the SDG team and ensure that data will be there and can be consumed in a predictable way.

**Comment by russellb** [comment]
Right now the data format is the same as it was before in the CLI. That data does not exist in the output right now.

**Comment by nathan-weinberg** [comment]
Ack @russellb - is the plan to have that information added to the output? This is an example of the sample data I'm basing the above assumptions off of: https://github.com/nathan-weinberg/eval/blob/test/tests/testdata/sdg/tonsil_data.jsonl

cc @danmcp

**Comment by russellb** [comment]
You should be looking at data generated by the CLI. I don’t think that’s where that data came from.

**Comment by nathan-weinberg** [comment]
@russellb sounds good, @aakankshaduggal and I are going to talk about this more later today, cc @oindrillac

**Comment by nathan-weinberg** [comment]
@russellb @oindrillac i just spoke with @aakankshaduggal and the data format y'all are planning to do for training in the issue above is the same format we are expecting for Eval, so we should be good on our side as soon as that's complete!

**Comment by russellb** [comment]
assuming someone is going to adjust the CLI training code for the new format as well, then?

**Comment by nathan-weinberg** [comment]
This issue really only pertains to Eval, so can't speak to Training
