### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/eval#36]
The library currently doesn't have robust error handling. We should implement this with our custom error classes and do appropriate handling on the CLI side.

**Comment by ktam3** [comment]
Confirmed by Dan in Eval slack as closed/fixed

**Comment by danmcp** [comment]
> Confirmed by Dan in Eval slack as closed/fixed

If additional error handling is needed, we should open new specific issues for the cases that are missed.
